TerraImpact/config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users, :controllers => { registrations: 'registrations', sessions: "sessions"} 
  resources :impacts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root "impacts#index"
  resources :users, except: :create
    post 'create_user' => 'users#create', as: :create_user   
end

TerraImpact/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    include Friendlyable
    validates :username, presence: :true, uniqueness: { case_sensitive: false }
    validates :name, presence: :true, uniqueness: { case_sensitive: false }
    validates :description, length: { maximum: 280 }
    devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
    
    has_one_attached :avatar
    
    has_many :impacts, dependent: :destroy
end

TerraImpact/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
    
    prepend_before_action :check_captcha, only: [:create]

      private

      def check_captcha
        @recaptcha_success = verify_recaptcha
        if @recaptcha_success && @student.save
          self.resource = resource_class.new
          resource.validate # Look for any other validation errors besides Recaptcha
          respond_with_navigational(resource) { render :new }
        else
            clean_up_passwords(resource)
            flash[:notice] = flash[:notice].to_a.concat resource.errors.full_messages
        end
      end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

TerraImpact/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order("id")
    if params[:username]
        @normal_users = User.where('admin = ? AND username ILIKE ?', false, "%#{params[:username]}%").order("id")
    else
        @normal_users = User.where('admin = ? ', false).order("id")
    end
    @admins = User.where('admin = ? ', true).order("id")
    fresh_when etag: @normal_users
    fresh_when etag: @admins
  end
    
  def show
    @user = User.friendly.find(params[:id])
    fresh_when etag: @user
  end
    
  def new
    @user = User.new
  end
    
  def edit
      @user = User.friendly.find(params[:id]) 
  end
    
  def destroy
    @user = User.friendly.find(params[:id]) 
    @user.destroy
    redirect_to users_path, :flash => { :notice => 'User was successfully deleted.' }
  end
    
  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, :flash => { :notice => 'User was successfully created.' }
    else
      render :action => 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.friendly.find(params[:id])

    if @user.update_attributes(user_params)
      sign_in(@user, :bypass => true) if @user == current_user
      redirect_to @user, :flash => { :notice => 'User was successfully updated.' }
    else
      render :action => 'edit'
    end
      
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
  end
    
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :avatar, :description, :admin)
    end  
end

TerraImpact/app/helpers/users_helper.rb
module UsersHelper
end

TerraImpact/app/views/users/_create-user.html.erb
<div class="section">
    <div class="container">
        <div class="columns is-centered">
        
        <div class="column is-5">
        
        <% if @user.errors.any? %>
            <div id="error_explanation">
                <h5 class="has-text-danger"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being registered:</h5>
                <ul>
                  <% @user.errors.full_messages.each do |msg| %>
                    <li class="has-text-danger"> * <%= msg %></li>    
                  <% end %>
                </ul>
             </div>
        <% end %>
        <%= simple_form_for(@user, url: create_user_path) do |f| %>
        <%= f.error_notification %>
        

        <h1 class="title">Create a new user</h1>
        
        <div class="field">
            <div class="control">
               <p class="has-text-weight-bold">Profile Photo *Optional</p>
                <%= f.file_field :avatar,
                autofocus: true,
                input_html: { class:"input" }, wrapper:false,label_html: { class:"label"} %>
            </div>        
        </div>
        
        <div class="field">
            <div class="control">
               <p class="has-text-weight-bold">User Description *Optional</p>
                <%= f.input :description,
                hint: "Limit to 280 words",
                autofocus: true,
                input_html: { class:"input" }, wrapper:false,label_html: { class:"label"} %>
            </div>        
        </div>
        
        <div class="field">
            <div class="control">
                <%= f.input :username,
                required: true,
                :required => 'required',
                autofocus: true,
                input_html: { class:"input" }, wrapper:false,label_html: { class:"label"} %>
            </div>        
        </div>
        
        <div class="field">
            <div class="control">
                <%= f.input :name,
                required: true,
                :required => 'required',
                autofocus: true,
                input_html: { class:"input" }, wrapper:false,label_html: { class:"label"} %>
            </div>        
        </div>
        
        <div class="field">
            <div class="control">
                <%= f.check_box :admin,
                hint: "Check the box if the user is admin",
                input_html: { class:"input" }, wrapper:false,label_html: { class:"label"} %> Is the user an admin? (optional)
            </div>        
        </div>

        <div class="field">
            <div class="control">
                <%= f.input :email,
                required: true,
                autofocus: true,
                input_html: { class:"input" }, wrapper:false,label_html: { class:"label"} %>
            </div>        
        </div>
        
        
        <div class="field">
            <div class="control">
                <%= f.input :password,
                required: true,
                hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                input_html: { class:"input" }, wrapper:false, label_html: { class:"label"} %>
            </div>        
        </div>
        
        <div class="field">
            <div class="control">
                <%= f.input :password_confirmation,
                required: true,
                input_html: { class:"input" }, wrapper:false, label_html: { class:"label"} %>
            </div>        
        </div>

        <div class="field">
            <div class="control">
            <%= f.button :submit, "Create", class:"button is-small is-info" %>
            </div>
            <% end %>
        </div>
        
        </div>
        </div>
    </div>
</div>

TerraImpact/app/views/users/_edit-user.html.erb
<div class="section">
    <div class="container">
        <div class="columns is-centered">
        
        <div class="column is-5">
        <h4><i class="fas fa-chevron-left"></i>  <%= link_to 'Back', impacts_path %></h4>
        <br/>
        
        <% if @user.errors.any? %>
            <div id="error_explanation">
                <h5 class="has-text-danger"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being registered:</h5>
                <ul>
                  <% @user.errors.full_messages.each do |msg| %>
                    <li class="has-text-danger"> * <%= msg %></li>    
                  <% end %>
                </ul>
             </div>
        <% end %>
        <%= simple_form_for(@user) do |f| %>
        <%= f.error_notification %>
        

        <h1 class="title">Edit <%= @user.name %></h1>
        
        <div class="field">
            <div class="control">
               <p class="has-text-weight-bold">Profile Photo</p>
                <%= f.file_field :avatar,
                required: false,
                autofocus: true,
                input_html: { class:"input" }, wrapper:false,label_html: { class:"label"} %>
            </div>        
        </div>
        
        <div class="field">
            <div class="control">
               <p class="has-text-weight-bold">User Description *Optional</p>
                <%= f.input :description,
                hint: "Limit to 280 words",
                autofocus: true,
                input_html: { class:"input" }, wrapper:false,label_html: { class:"label"} %>
            </div>        
        </div>
        
        <div class="field">
            <div class="control">
                <%= f.input :username,
                required: false,
                autofocus: true,
                input_html: { class:"input" }, wrapper:false,label_html: { class:"label"} %>
            </div>        
        </div>
        
        <div class="field">
            <div class="control">
                <%= f.input :name,
                required: false,
                autofocus: true,
                input_html: { class:"input" }, wrapper:false,label_html: { class:"label"} %>
            </div>        
        </div>
        
        <div class="field">
            <div class="control">
                <%= f.check_box :admin,
                hint: "Check the box if the user is admin",
                input_html: { class:"input" }, wrapper:false,label_html: { class:"label"} %> Is the user an admin? (optional)
            </div>        
        </div>

        <div class="field">
            <div class="control">
            <%= f.button :submit, "Update", class:"button is-small is-info" %>
            </div>
            
        </div>
        <% end %>
        
        </div>
        </div>
    </div>
</div>

TerraImpact/app/views/users/_profile.html.erb
<div class="is-8 column">
     <h4><i class="fas fa-chevron-left"></i>  <%= link_to 'Back', impacts_path %></h4>
     <br/>
      <div class="box">
         <article class="media">
                  <div class="media-left">
                      <figure class="is-128x128 image">
                          <% if @user.avatar.attached? %>
                                <%= link_to image_tag(@user.avatar, class: "profile-img"), user_path(@user), class: "colorbox" %>
                          <% else %>
                                <%= link_to gravatar_image_tag(@user.email, size: 64, alt: @user.name), user_path(@user), class: "colorbox" %>
                          <% end %>
                      </figure>
                  </div>
                  <div class="media-content">
                      <div class="content">
                          <br>
                          <h3><%= @user.name %></h3>
                          <h4>@<%= @user.username %></h4>
                      </div>
                  </div>
        </article>
        <div class="description">
            <p><%= @user.description %></p>
        </div>
        <hr/>
        <div class="columns has-text-centered">
            <div class="column ">
                <h5 class="has-text-grey">Impacts</h5>
                <h4 class="has-text-weight-bold has-text-info"><%= @user.impacts.count %></h4>
            </div>
            <div class="column ">
                <h5 class="has-text-grey">Joined</h5>
                <h4 class="has-text-weight-bold has-text-info"><%= @user.created_at.strftime("%d %b %Y") %></h4>
            </div>
        </div>
      </div>
  <br/>
  
  <h2><%= @user.name %>'s Impacts</h2>

<% @user.impacts.each do |impact| %>
      <div class="box">
          <article class="media">
              <div class="media-left">
                  <figure class="is-64x64 image">
                        <% if @user.avatar.attached? %>
                                <%= link_to image_tag(@user.avatar, class: "profile-img"), user_path(@user), class: "colorbox" %>
                          <% else %>
                                <%= link_to gravatar_image_tag(@user.email, size: 64, alt: @user.name), user_path(@user), class: "colorbox" %>
                          <% end %>
                  </figure>
              </div>
              <div class="media-content">
                  <div class="content">
                      <p><strong><%= @user.name %></strong> <span class="has-text-weight-light">@<%= @user.username %>  </span>&nbsp;<span class="has-text-grey-light"><i class="far fa-calendar"></i><%= impact.created_at.strftime("%d %b %Y") %></span></p>

                      <p><%= impact.impact %></p>
                        <br>
                      <p class="has-text-grey-light"><i class="fas fa-tags"></i> <%= impact.category %></p>
                  </div>
                  <% if user_signed_in? && current_user.admin? %>
                      <div class="level">
                          <div class="is-mobile level-left">
                              <%= link_to impact, class: "level-item" do %>
                                  <span class="icon"><i class="fas fa-link"></i></span>
                              <% end %>
                              <%= link_to edit_impact_path(impact), class: "level-item" do %>
                                  <span class="icon"><i class="fas fa-pencil-alt"></i></span>
                              <% end %>
                              <%= link_to impact, method: :delete, data: {confirm: "Do you want to delete this item?"} do %>
                                  <span class="icon"><i class="fas fa-trash"></i></span>
                              <% end %>
                          </div>
                      </div>
                  <% end %>
              </div>
          </article>
      </div>
<% end %>
</div>

TerraImpact/app/views/users/_users-detail.html.erb
<div class="section">
    <div class="columns is-centered">
        <div class="column is-10">
         <div class="add-user">
              <%= link_to new_user_path, class: "button is-info" do %>
                  <span><i class="fas fa-plus"></i>  Create New User</span>
              <% end %>
          </div>
          <br/>
          <div class="tabs is-boxed is-fullwidth is-large">
              <ul>
                  <li class="is-active"><a>Normal Users</a></li>
                  <li><a>Admins</a></li>
              </ul>
          </div>
          <div class="tabs-content">
              <div class="tab-content is-active">
                    <%= form_tag(users_path, method: :get) do %>
                      Username <%= text_field_tag :username, params[:username] %>
                      <%= submit_tag 'Search', class: "button is-info is-small", name: nil %>
                      <%= link_to users_path, class: "button is-info is-small" do %>
                          <span><i class="fas fa-undo"></i> Cancel</span>
                      <% end %>
                    <% end %>
                    <br/>
                   <table class="table">
                        <thead>
                        <tr>
                          <th><abbr title="ID">ID</abbr></th>
                          <th><abbr title="Avatar">Avatar</abbr></th>
                          <th><abbr title="Name">Name</abbr></th>
                          <th><abbr title="Username">Username</abbr></th>
                          <th><abbr title="Email">Email</abbr></th>
                          <th><abbr title="Description">Description</abbr></th>
                          <th><abbr title="Action" class="is-centered">Action</abbr></th>
                        </tr>
                        </thead>
                        <tbody>
                        <% @normal_users.each do |user| %>
                            <tr>
                            <th><%= user.id %></th>
                            <td>
                                <figure class="image is-48x48">
                                <% if user.avatar.attached? %>
                                    <%= link_to image_tag(user.avatar, class: "profile-img"), user_path(user), class: "colorbox" %>
                                <% else %>
                                    <%= link_to gravatar_image_tag(user.email, size: 64, alt: user.name), user_path(user), class: "colorbox" %>
                                <% end %>
                                </figure>
                            </td>
                            <td><%= link_to user.name, user %></td>
                            <td>@<%= user.username %></td>
                            <td><%= user.email %></td>
                            <td><%= user.description %></td>
                            <td>
                               <div class="level">
                                    <%= link_to user, class: "level-item" do %>
                                        <span class="icon"><i class="fas fa-link"></i></span>
                                    <% end %>
                                    <%= link_to edit_user_path(user), class: "level-item" do %>
                                        <span class="icon"><i class="fas fa-pencil-alt"></i></span>
                                    <% end %>
                                    <%= link_to user, method: :delete, data: {confirm: "Do you want to delete this item?"}, class: "level-item" do %>
                                        <span class="icon"><i class="fas fa-trash"></i></span>
                                    <% end %>
                                </div>
                            </td>
                            </tr>
                        <% end %>
                        </tbody>
                    </table>
                </div>
                <div class="tab-content">
                   <table class="table">
                        <thead>
                        <tr>
                          <th><abbr title="ID">ID</abbr></th>
                          <th><abbr title="Avatar">Avatar</abbr></th>
                          <th><abbr title="Name">Name</abbr></th>
                          <th><abbr title="Username">Username</abbr></th>
                          <th><abbr title="Email">Email</abbr></th>
                          <th><abbr title="Description">Description</abbr></th>
                          
                        </tr>
                        </thead>
                        <tbody>
                        <% @admins.each do |admin| %>
                            <tr>
                            <th><%= admin.id %></th>
                            <td>
                                <figure class="image is-48x48">
                                <% if admin.avatar.attached? %>
                                    <%= link_to image_tag(admin.avatar, class: "profile-img"), user_path(admin), class: "colorbox" %>
                                <% else %>
                                    <%= link_to gravatar_image_tag(admin.email, size: 64, alt: admin.name), user_path(admin), class: "colorbox" %>
                                <% end %>
                                </figure>
                            </td>
                            <td><%= link_to admin.name, admin %></td>
                            <td>@<%= admin.username %></td>
                            <td><%= admin.email %></td>
                            <td><%= admin.description %></td>
                            
                            </tr>
                        <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

TerraImpact/app/views/users/edit.html.erb
<% if user_signed_in? && current_user.admin? %>
      <%= render 'edit-user' %>
<% else %>
      <%  controller.redirect_to root_path, alert: 'Admins only!' %> 
<% end %>

TerraImpact/app/views/users/index.html.erb
<div class="column">
    
    <div class="panel-heading">Interested? Follow them!</div>
    <% @users.each do |user| %>
    <div class="panel-block">
        <div class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/images/placeholders/32x32.png">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p><%= user.name %>  <strong>@<%= user.username %></strong></p>
                    
                </div>
            </div>
        </div>
    </div>
    <% end %>
</div>

TerraImpact/app/views/users/new.html.erb
<% if user_signed_in? && current_user.admin? %>
      <%= render 'create-user' %>
<% else %>
      <%  controller.redirect_to root_path, alert: 'Admins only!' %> 
<% end %>

TerraImpact/app/views/users/show.html.erb
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <%= render 'profile' %>
        </div>
    </div>
</section>
     